document.writeln(" <img src=\'../img/anzhang/index-footer-bg.png\' alt=\'\' style=\'position: absolute;z-index: -1;\'>");
document.writeln("        <div class=\'b_wrap\'>");
document.writeln("            <div class=\'ui grid clearfix\' style=\'padding-bottom: 76px;\'>");
document.writeln("                <div class=\'b_footer_q\'>");
document.writeln("                    <h2>联系我们</h2>");
document.writeln("                    <p>");
document.writeln("                        公司地址：<span>浙江省杭州市富阳区东洲街道十三号路完整家居</span> 联系电话：");
document.writeln("                        <span>800171892 </span> 网上商城：");
document.writeln("                        <span><a href=\'http://www.dongjianhome.com\'>www.dongjianhome.com</a></span>");
document.writeln("                    </p>");
document.writeln("                    <h2 class=\'b_footer_v\'>友情链接</h2>");
document.writeln("                    <div class=\'b_footer_h\'>");
document.writeln("                        <ul>");
document.writeln("                            <ul>");
document.writeln("                                <li><a href=\'#\'>安卓在线</a></li>");
document.writeln("                                <li><a href=\'#\'>游戏狗</a></li>");
document.writeln("                                <li><a href=\'#\'>搜狐高速</a></li>");
document.writeln("                                <li><a href=\'#\'>优亿市场</a></li>");
document.writeln("                                <li><a href=\'#\'>木蚂蚁应用市场</a></li>");
document.writeln("                                <li><a href=\'#\'>手游天下</a></li>");
document.writeln("                                <li><a href=\'#\'>苹果猫人吧</a></li>");
document.writeln("                                <li style=\'visibility: hidden;\'><a href=\'#\'>苹果猫人吧</a><a href=\'#\'>苹果猫人吧</a></li>");
document.writeln("                            </ul>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'b_footer_h\'>");
document.writeln("                        <ul>");
document.writeln("                            <li><a href=\'#\'>机锋网</a></li>");
document.writeln("                            <li><a href=\'#\'>安卓市场</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'b_footer_z\'>");
document.writeln("                   <div class=\'ui image fluid\'>");
document.writeln("                        <img src=\'../img/anzhang/index-footer-erweima.png\' alt=\'\'>");
document.writeln("                    </div>");
document.writeln("                    <p>微信关注我们</p>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div style=\'border-bottom: 1px dashed #ababab;\'></div>");
document.writeln("            <div class=\'b_footer_g clearfix\'>");
document.writeln("                <div class=\'b_footer_l\'>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'#\'>关于完整家居</a></li>");
document.writeln("                        <li><a href=\'#\'>更新日志</a></li>");
document.writeln("                        <li><a href=\'#\'>新手帮助</a></li>");
document.writeln("                   </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'b_footer_d\'>");
document.writeln("                    <p>Copyright©2017-2017fcwr All Rights Reserved.</p>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");