document.writeln("<div class=\'ui very padded segment h-nav\'  style='margin-top: 0'>");
document.writeln("<div class=\'ui container middle aligned gird\'>");
document.writeln("<div class=\'four wide column \'>");
document.writeln("<div class=\'ui secondary menu \'>");
document.writeln("<div class=\'h-img\'>");
document.writeln("<a href=\'../html/index.html\'><img src=\'../img/index/logo.png\'></a>");
document.writeln("</div>");
document.writeln("<div class=\'ui right secondary  nine item menu h-men\'>");
document.writeln("<a class=\'item \' href=\'../html/index.html\'>首页</a>");
document.writeln("<a class=\'item \' href=\'../html/Company-profile.html\'>公司简介</a>");
document.writeln("<a class=\'item \' href=\'../html/Physical-store.html\'>实体门店</a>");
document.writeln("<a class=\'item \' href=\'../html/Electronic-business-platform.html\'>电商平台</a>");
document.writeln("<a class=\'item \' href=\'../html/Excellent-treasure.html\'>优采宝</a>");
document.writeln("<a class=\'item \' href=\'../html/Warehouse-ogistics.html\'>仓配物流</a>");
document.writeln("<a class=\'item \' href=\'../html/Installation-maintenance.html\'>安装维修</a>");
document.writeln("<a class=\'item \' href=\'../html/Human-resources.html\'>人力资源</a>");
document.writeln("<a class=\'item iteml \'><img src=\'../img/index/search.png\' ></a>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");